-- migration: seed ingredients
-- Uses ingredient names that are present on the homePage view.

INSERT IGNORE INTO `ingredients` (`name`) VALUES
  ('Apples'),
  ('Bananas'),
  ('Lemons'),
  ('Pears'),

  ('Tomatoes'),
  ('Potatoes'),
  ('Onions'),
  ('Garlic'),
  ('Carrots'),
  ('Bell Peppers'),
  ('Broccoli'),
  ('Cauliflower'),
  ('Mushrooms'),
  ('Zucchini'),
  ('Cucumber'),
  ('Salad / Lettuce'),

  ('Eggs'),
  ('Milk'),
  ('Butter'),
  ('Cheddar Cheese'),
  ('Cream Cheese'),
  ('Yogurt'),

  ('Chicken Breast'),
  ('Chicken (in General)'),
  ('Ground Beef'),
  ('Pork'),
  ('Fish (in General)'),
  ('Bacon'),

  ('Flour'),
  ('Sugar'),
  ('Brown Sugar'),
  ('Salt'),
  ('Black Pepper'),
  ('Olive Oil'),
  ('Vegetable Oil'),
  ('Vinegar'),
  ('Baking Powder'),
  ('Baking Soda'),
  ('Bread (in General)'),
  ('Rice'),
  ('Pasta'),
  ('Tortillas'),
  ('Ketchup'),
  ('Mayonnaise'),
  ('Mustard'),
  ('Soy Sauce'),
  ('Hot Sauce'),
  ('Chicken Broth / Stock'),
  ('Tomato Sauce / Passata'),
  ('Canned Tomatoes'),
  ('Beans (canned)'),
  ('Oregano'),
  ('Basil'),
  ('Paprika'),
  ('Cinnamon'),
  ('Garlic Powder'),
  ('Onion Powder');
